# Generated by Django 2.1.7 on 2019-03-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_title', models.CharField(max_length=140)),
                ('note_text', models.TextField()),
                ('date_created', models.DateField(auto_now=True)),
                ('expiry_date', models.DateField()),
                ('url', models.URLField()),
                ('note_type', models.CharField(choices=[('N', 'Note'), ('E', 'Event'), ('T', 'Task')], max_length=1)),
            ],
        ),
    ]
