# Generated by Django 2.1.7 on 2019-03-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bj', '0003_remove_tags_note_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag_notes',
            name='note_id',
        ),
        migrations.RemoveField(
            model_name='tag_notes',
            name='tag_id',
        ),
        migrations.AddField(
            model_name='tags',
            name='notes',
            field=models.ManyToManyField(to='bj.Notes_Notes'),
        ),
        migrations.DeleteModel(
            name='Tag_Notes',
        ),
    ]
