# Generated by Django 2.1.7 on 2019-03-25 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bj', '0004_auto_20190325_0743'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
